Repository wizardsardine/liana, pull requests merged in 2024-11, with the labels that each got.

#1419 gui(edit key modal): increase size of the closing icon
  gui/src/installer/view/editor/mod.rs
Labels: Nice to have

#1400 gui: add support for tapminiscript on bitbox02
  gui/src/app/state/psbt.rs
  gui/src/hw.rs
Labels: Signing devices, Nice to have

#1428 gui(installer): align title & descrpition in path cards
  gui/src/installer/view/editor/mod.rs
Labels: Nice to have

#1404 Refac pagination: sort list in async command
  gui/src/app/message.rs
  gui/src/app/state/mod.rs
  gui/src/app/state/transactions.rs
  gui/src/app/view/home.rs
  gui/src/app/view/transactions.rs
  gui/src/daemon/model.rs
Labels: Nice to have

#1437 gui: reload home if wallet is not syncing
  liana-gui/src/app/state/mod.rs
  liana-gui/src/app/wallet.rs
Labels: GUI, Enhancement
